# Generated by Django 4.2.6 on 2023-10-21 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_alter_dataset_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Logistic',
            new_name='Linear_ALGo',
        ),
    ]
